language: php

php:
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer install

script:
  - php vendor/codeception/codeception/codecept run integration --coverage-xml

after_success:
    - bash <(curl -s https://codecov.io/bash)